### ISSUE TITLE
Installation error on latest core22 pc-gadget

### ISSUE THREAD

**Issue by farshidtz** [canonical/edgex-ubuntu-core-testing#1]
The UC installation fails with the following log:
```
[  OK  ] Started /run/mnt/snapd/usr/lib/snapd/snapd.
[    8.800399] systemd[1]: Started /run/mnt/snapd/usr/lib/snapd/snapd.
[    8.801206] snapd[892]: firstboot.go:401: failed to auto-import assertions: open /var/lib/snapd/seed/systems/20230517/auto-import.assert: no such file or directory
[   10.031860] systemd-timesyncd[844]: Network configuration changed, trying to establish connection.
[   10.038923] snapd[892]: stateengine.go:149: state ensure error: devicemgr: cannot seed: snap "pc" assumes unsupported features: snapd2.59.3 (try to refresh snapd)
[   12.975541] systemd[1]: Created slice Slice /system/console-conf.
[   40.336100] systemd-resolved[854]: Clock change detected. Flushing caches.
[   40.336606] systemd-timesyncd[844]: Initial synchronization to time server 185.125.190.58:123 (ntp.ubuntu.com).
[   98.020608] systemd[1]: getty@tty1.service: start-pre operation timed out. Terminating.
[   98.021060] systemd[1]: getty@tty1.service: Control process exited, code=killed, status=15/TERM
[   98.021140] systemd[1]: getty@tty1.service: Failed with result 'timeout'.
[   98.022444] systemd[1]: getty@tty1.service: Scheduled restart job, restart counter is at 1.
[   98.022531] systemd[1]: Stopped Getty on tty1.
[   98.023267] systemd[1]: Started Getty on tty1.
[  188.270217] systemd[1]: getty@tty1.service: start-pre operation timed out. Terminating.
[  188.270633] systemd[1]: getty@tty1.service: Control process exited, code=killed, status=15/TERM
[  188.270736] systemd[1]: getty@tty1.service: Failed with result 'timeout'.
[  188.272781] systemd[1]: getty@tty1.service: Scheduled restart job, restart counter is at 2.
[  188.273082] systemd[1]: Stopped Getty on tty1.
[  188.274056] systemd[1]: Started Getty on tty1.
```

To make the UC image build work work, one should checkout commit [`1779b0de4e022ddcbefd782e0523ee9c0c7f1dea`](https://github.com/snapcore/pc-gadget/commit/1779b0de4e022ddcbefd782e0523ee9c0c7f1dea) for the pc-gadget.

_Originally posted by @farshidtz in https://github.com/canonical/edgex-snap-testing/pull/205#pullrequestreview-1434542853_

**Comment by farshidtz** [comment]
Apparently, the latest pc gadget needs snapd 2.59.4, currently on latest/candidate.

**Comment by farshidtz** [comment]
We have the following potential solutions:
1. checkout the last compatible commit of pc-gadget repo → quick and temporary fix
2. switch the snapd channel in model assertion → a fix for now but not a long-term solution
3. download the gadget from store, unsquash, make our customizations, squash and sideload → easy and ugly
4. stage the latest/stable pc-gadget into a new one and add our customizations → recommended

I suggest we go with 1 and add an issue to implement 4.

**Comment by tonyespy** [comment]
I'm having a hard time understanding this issue, as the description lacks context/detail...

That said, as I mentioned in our sync yesterday, the staging approach you describe is not recommended.

**Comment by farshidtz** [comment]
@tonyespy At the time of creation this issue, the core22 pc-gadget (branch `22`) source had an assume field requiring snapd 2.59.3, while the latest/stable snapd was 2.59.2 or smaller. The requirement is added in https://github.com/snapcore/pc-gadget/commit/1ba317cf25a2c4f45e80bccbe8b2cf03a52f3e09

The error message preventing the installation was `[   10.038923] snapd[892]: stateengine.go:149: state ensure error: devicemgr: cannot seed: snap "pc" assumes unsupported features: snapd2.59.3 (try to refresh snapd)`. 

In https://github.com/canonical/edgex-ubuntu-core-testing/issues/1#issuecomment-1558669715, I explained some of the workarounds and the recommendation from a UC engineer.

Note that right now the latest/stable snapd is 2.59.4 so using the latest dev core22 pc-gadget code should work fine.
